# Generated by Django 5.1.7 on 2025-04-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_custom_admin',
            field=models.BooleanField(default=False),
        ),
    ]
