# Generated by Django 5.1.7 on 2025-04-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_is_custom_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedloginattempt',
            name='observation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
